### ISSUE TITLE
support BooleanType?

### ISSUE THREAD

**Issue by zhao41654828** [spullara/cli-parser#16]
Hi. I has a question recently.
When I set the Boolean field to "false", but after java run, the Boolean field value is true.
My version is 1.1.2.
After reading the source code , I found:
```
    private static Object consumeArgumentValue(Class<?> type, Argument argument, Iterator<String> i) {
        Object value;
        if (type == Boolean.TYPE || type == Boolean.class) {
            value = true;
        } else {
            if (i.hasNext()) {
                value = i.next();
                i.remove();
            } else {
                throw new IllegalArgumentException("Must have a value for non-boolean argument " + argument.value());
            }
        }
        return value;
    }
```
It likes, the Boolean field is always setted to true value. 
I don't know why handle the Boolean Type like this.

**Comment by jordanbancino** [comment]
When running your project, are you specifying the flag that triggers the Boolean on the command line? If so, this is expected behaviour. It should be setting the Boolean true when it's argument is specified on the command line. If that is not the case, can you please post the code you are using so that I can try and replicate this issue?

**Comment by spullara** [comment]
Boolean fields are treated as flags. They are false if not present, true if present. You don't set the value on them.
